services:
  #############################
  # Nextext
  #############################
  nextext:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HF_CACHE:-${USERPROFILE:-$HOME}/.cache/huggingface}:/root/.cache/huggingface
      - ${APPDATA:-${HOME}}/nltk_data:/root/nltk_data
    ports:
      - "8501:8501"
    environment:
      - API_KEY=${API_KEY}
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=8192
      - USE_DEVICE=auto
      - UV_TORCH_BACKEND=auto
    extra_hosts:
      - "host.docker.internal:host-gateway"

  #############################
  # Ollama
  #############################
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama
