[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nextext"
version = "0.8.0"
description = "Audio transcription and analysis."
authors = [
    { name = "nos-tromo" }
]
requires-python = ">=3.11,<3.12"
readme = { file = "README.md", content-type = "text/markdown" }
dependencies = [
    "accelerate>=1.1.1",
    "arabic-reshaper>=3.0.0",
    "bertopic>=0.16.4",
    "camel-tools>=1.5.2",
    "huggingface-hub>=0.26.2",
    "langdetect>=1.0.9",
    "llvmlite>=0.41.0",
    "matplotlib>=3.9.2",
    "networkx>=3.4.2",
    "nltk>=3.9.1",
    "numpy>=1.26.4",
    "ollama>=0.4.8",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pillow>=11.0.0",
    "pip>=25.0.1",
    "pyannote-audio>=3.3.2",
    "pyarabic>=0.6.15",
    "pycountry>=24.6.1",
    "python-bidi>=0.6.3",
    "python-dotenv>=1.0.1",
    "python-multipart>=0.0.20",
    "pyvis>=0.3.2",
    "scikit-learn>=1.5.2",
    "sentence-transformers>=4.1.0",
    "spacy>=3.8.4",
    "streamlit>=1.44.1",
    "textual>=4.0.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "transformers>=4.46.2",
    "umap-learn>=0.5.7",
    "watchdog>=6.0.0",
    "whisperx>=3.3.4",
    "wordcloud>=1.9.4",
]

[project.scripts]
load-spacy-models = "nextext.utils.spacy_model_loader:main"
nextext = "nextext.app:cli"
nextext-cli = "nextext.cli:main"

[project.urls]
Repository = "https://github.com/nos-tromo/Nextext.git"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.uv.sources]
nextext = { workspace = true }
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { index = "pytorch-cpu",  marker = "sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { index = "pytorch-cpu",  marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
  